In [2]:
#http://theanets.readthedocs.org/en/stable/
from module_imports import *
from download_data import *
from import_data import *

import theanets
from sklearn.datasets import make_classification
from sklearn.metrics import confusion_matrix

%matplotlib inline

In [ ]:
stock_df, prediction_df = pd.DataFrame(), pd.DataFrame()
source = "Q"
binarize = True
gt = 2.0
lt = 20.0
vol = 100
if source == "Q":
    stock_df, prediction_df = get_quandl_data(binarize=True, gt=gt, lt=lt, vol=vol)
elif source == "G":
    stock_df, prediction_df = get_goog_data(binarize=True, gt=gt, lt=lt, vol=vol)

In [ ]:
y = stock_df['label'].values
y = y.reshape(y.shape[0], 1)

X_df = stock_df.drop('label', axis=1)
X = X_df.values

print X.shape, y.shape
X_df.tail()

In [4]:
# Create a classification dataset.
X, y = make_classification(
    n_samples=3000, n_features=100, n_classes=10, n_informative=10)
X = X.astype('f')
y = y.astype('i')
cut = int(len(X) * 0.8)  # training / validation split
train = X[:cut], y[:cut]
valid = X[cut:], y[cut:]

# Build a classifier model with 100 inputs and 10 outputs.
exp = theanets.Experiment(theanets.Classifier, layers=(100, 10))

# Train the model using SGD with momentum.
exp.train(train, valid, algorithm='sgd', learning_rate=1e-4, momentum=0.9)

# Show confusion matrices on the training/validation splits.
for label, (X, y) in (('training:', train), ('validation:', valid)):
    print(label)
    print(confusion_matrix(y, exp.network.predict(X)))
    print classification_report(y, exp.network.predict(X))

training:
[[133  10  17  14  21  13  10   8  14   2]
 [  4 127  29   6  13  20  10   4  11  13]
 [ 23  16 139  19   6   6   8   0  12   9]
 [ 29  10  15  92   7  21  23  20   9  24]
 [ 31  37  12   1 102  16  14   8  10   4]
 [ 25  35  21  21  17  54  21  15  13  15]
 [ 13  10   4  28  15  21 124   3  14   7]
 [  8   9   8   8   2   8  15 120  24  39]
 [ 10  22  15  13   7  26  18  30  74  25]
 [ 20  18  25  10   3   5   7  39  13 101]]
             precision    recall  f1-score   support

          0       0.45      0.55      0.49       242
          1       0.43      0.54      0.48       237
          2       0.49      0.58      0.53       238
          3       0.43      0.37      0.40       250
          4       0.53      0.43      0.48       235
          5       0.28      0.23      0.25       237
          6       0.50      0.52      0.51       239
          7       0.49      0.50      0.49       241
          8       0.38      0.31      0.34       240
          9       0.42      